### PR TITLE
Feature/geocode fetch

### PR DESCRIPTION
**Pull request by Bradford-Lee**

### CODE REVIEW

**Review by kuocats — APPROVED** [review]

**Review by itcreativeusa — COMMENTED** [review]
looks great

**Comment by itcreativeusa** [comment]
good

**Comment by itcreativeusa** [comment]
good

**Review by itcreativeusa — COMMENTED** [review]
good

**Review by itcreativeusa — APPROVED** [review]

**Review by neilmkflyingk — APPROVED** [review]

**Pull request merged**
